### PR TITLE
Remove wkhtmltopdf and layers + update Readme

### PR DESCRIPTION
**Pull request by gabriel-tessier**
I removed the reference to wkhtmltopdf and layer for Weasyprint as it only run on old version V52 released in 2020.

I add reference to CDK in the top readme but as I don't have any knowledge in CDK I kept all the code as it, I don't know if it's building the layers or the container. If it's only deal with layer I can remove it.

If you can review, I hope I did not remove too much.

### CODE REVIEW

**Comment by kalekseev** [comment]
Judging by issues people still use native weasyprint layer so I would prefer to keep it and wait until a new lambda runtime released with latest pango.

**Comment by kalekseev** [comment]
weasyprint now works as layer with python3.12 runtime

**Comment by hoangquochung1110** [comment]
Hi @kalekseev 

First of all, thank you for the fantastic repo

I'm also developing a utils feature to facilitate pdf generation in my web app.

wkhtmltopdf helps me a lot to do it but as soon as I learnt your repo noticing this tool was removed in your repo. Could you kindly share what is your motivation ? Thank you

**Comment by kalekseev** [comment]
@hoangquochung1110 wkhtmltopdf is unsupported for quite some time, the repo was archived, also check https://wkhtmltopdf.org/status.html especially recommendations section. The only reason wkhtmltopdf was added to this project is because we had a client whom we moved to cloud thus had to run wkhtmltopdf in lambda.

Also the tool is not removed in this repo but it won't be migrated to new runtimes and users should be discuoraged to start using it in new projects.

**Pull request closed without merging**
